---
abstract: 'PKCS #5 v2.1: Password-Based Cryptography Standard.'
author:
  - '小山浩之 <oyama@module.jp>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.68, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Crypt-PKCS5
no_index:
  directory:
    - t
    - inc
requires:
  Digest::HMAC_SHA1: 0
  Digest::MD5: 0
version: 0.02
