# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Crypt-PKCS5
version:      0.01
version_from: lib/Crypt/PKCS5.pm
installdirs:  site
requires:
    Digest::HMAC_SHA1:             0
    Digest::MD5:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
